board_embedding_size: 256
board_intermediary_channels: 256
text_embedding_size: 256
ff_inner_channels: 512
num_heads: 8
transformer_blocks: 4
optimizer: sgd
lr: 0.08
conv_modules_count: 6
defaults:
  - /model/alphazero_residual_encoder_base@_here_