services:
  prepare_step:
    extends:
      file: ./model/docker-compose.yaml
      service: prepare_step

  model:
    extends:
      file: ./model/docker-compose.yaml
      service: model 

  proxy:
    extends:
      file: ./model/docker-compose.yaml
      service: proxy 

  nginx:
    build: ./frontend 
    ports:
      - "4200:80"
    depends_on:
      - model
      - proxy

volumes:
  venv:
