services:
  prepare_step:
    extends:
      file: ./model/docker-compose-dev.yaml
      service: prepare_step

  model:
    extends:
      file: ./model/docker-compose-dev.yaml
      service: model 

  proxy:
    extends:
      file: ./model/docker-compose-dev.yaml
      service: proxy 

  frontend:
    build: 
      context: frontend 
      dockerfile: ./Dockerfile.dev
    ports:
      - "4200:80"
    depends_on:
      - model
      - proxy
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf

volumes:
  venv:
