board_embedding_size: 64
text_embedding_size: 64
ff_inner_channels: 64
num_heads: 4
transformer_blocks: 2
optimizer: sgd
lr: 0.02
target_types_and_depth:
  -
    - 0
    - 2
  -
    - 1
    - 1
  -
    - 2
    - 3
  -
    - 4
    - 4
  -
    - 3
    - 5

defaults:
  - /model/actual_board_transformer_multiple_heads_base@_here_