@startuml
!pragma teoz true

actor User 
participant HistoryComponent 
participant GameStateService

opt Game state changed
  GameStateService --> HistoryComponent++: Set current move according to the current game state. 
end

User -> HistoryComponent: Click on displayed chess move or undo, redo, select first or last move via arrow keys.
HistoryComponent -> GameStateService: Seek to the selected user move.
HistoryComponent --> HistoryComponent : Render history with new selected move.

||0||
deactivate HistoryComponent



@enduml

